[project]
name = "lls-openai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-stack>=0.5.1",
    "llama-stack-client>=0.5.1",
]
